apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: mongodb-connection-disease-monitor
  options:
    disableNameSuffixHash: true
  literals:
    - host=mongodb-disease-monitor
    - port=27017

secretGenerator:
- name: mongodb-auth-disease-monitor
  options:
    disableNameSuffixHash: true
  literals:
  - username=admin
  - password=admin