/*
 * Disease Monitor Api
 *
 * Disease Monitor management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsmoleniak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package disease_monitor

import (
	"github.com/gin-gonic/gin"
)

type DiseaseMonitorCasesAPI interface {


    // CreateDiseaseCaseListEntry Post /api/disease-monitor/:regionId/entries
    // Saves new entry into disease case list 
     CreateDiseaseCaseListEntry(c *gin.Context)

    // DeleteDiseaseCaseEntry Delete /api/disease-monitor/:regionId/entries/:entryId
    // Deletes specific entry 
     DeleteDiseaseCaseEntry(c *gin.Context)

    // GetDiseaseCaseEntries Get /api/disease-monitor/:regionId/entries
    // Provides the disease case entries 
     GetDiseaseCaseEntries(c *gin.Context)

    // GetDiseaseCaseEntry Get /api/disease-monitor/:regionId/entries/:entryId
    // Provides details about disase case entry 
     GetDiseaseCaseEntry(c *gin.Context)

    // UpdateDiseaseCaseEntry Put /api/disease-monitor/:regionId/entries/:entryId
    // Updates specific entry 
     UpdateDiseaseCaseEntry(c *gin.Context)

}