/*
 * Disease Monitor Api
 *
 * Disease Monitor management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsmoleniak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package disease_monitor

import (
	"github.com/gin-gonic/gin"
)

type RegionsAPI interface {


    // CreateRegion Post /api/region
    // Saves new region definition 
     CreateRegion(c *gin.Context)

    // DeleteRegion Delete /api/region/:regionId
    // Deletes specific region 
     DeleteRegion(c *gin.Context)

}