/*
 * Disease Monitor Api
 *
 * Disease Monitor management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsmoleniak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package disease_monitor

import (
	"github.com/gin-gonic/gin"
)

type DiseaseTypesAPI interface {


    // GetDiseases Get /api/disease-monitor/:regionId/disease
    // Provides the list of diseases associated with region 
     GetDiseases(c *gin.Context)

}