/*
 * Disease Monitor Api
 *
 * Disease Monitor management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsmoleniak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package disease_monitor

import (
	"time"
)

type DiseaseCaseEntry struct {

	// Unique id of the disease case
	Id string `json:"id"`

	Disease Disease `json:"disease"`

	Patient Patient `json:"patient"`

	// Geographic latitude
	Latitude float64 `json:"latitude"`

	// Geographic longtitude
	Longtitude float64 `json:"longtitude"`

	// Reported time of the disease case.
	DiseaseStart time.Time `json:"diseaseStart"`

	// Reported time of disease end.
	DiseaseEnd time.Time `json:"diseaseEnd,omitempty"`
}
