/*
 * Disease Monitor Api
 *
 * Disease Monitor management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsmoleniak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package disease_monitor

// Disease - Describes disease
type Disease struct {

	Value string `json:"value"`

	Code string `json:"code"`

	TypicalDurationDays int32 `json:"typicalDurationDays,omitempty"`
}
