/*
 * Disease Monitor Api
 *
 * Disease Monitor management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xsmoleniak@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package disease_monitor

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the DiseaseMonitorCasesAPI part of the API
	DiseaseMonitorCasesAPI DiseaseMonitorCasesAPI
	// Routes for the DiseaseTypesAPI part of the API
	DiseaseTypesAPI DiseaseTypesAPI
	// Routes for the RegionsAPI part of the API
	RegionsAPI RegionsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateDiseaseCaseListEntry",
			http.MethodPost,
			"/api/disease-monitor/:regionId/entries",
			handleFunctions.DiseaseMonitorCasesAPI.CreateDiseaseCaseListEntry,
		},
		{
			"DeleteDiseaseCaseEntry",
			http.MethodDelete,
			"/api/disease-monitor/:regionId/entries/:entryId",
			handleFunctions.DiseaseMonitorCasesAPI.DeleteDiseaseCaseEntry,
		},
		{
			"GetDiseaseCaseEntries",
			http.MethodGet,
			"/api/disease-monitor/:regionId/entries",
			handleFunctions.DiseaseMonitorCasesAPI.GetDiseaseCaseEntries,
		},
		{
			"GetDiseaseCaseEntry",
			http.MethodGet,
			"/api/disease-monitor/:regionId/entries/:entryId",
			handleFunctions.DiseaseMonitorCasesAPI.GetDiseaseCaseEntry,
		},
		{
			"UpdateDiseaseCaseEntry",
			http.MethodPut,
			"/api/disease-monitor/:regionId/entries/:entryId",
			handleFunctions.DiseaseMonitorCasesAPI.UpdateDiseaseCaseEntry,
		},
		{
			"GetDiseases",
			http.MethodGet,
			"/api/disease-monitor/:regionId/disease",
			handleFunctions.DiseaseTypesAPI.GetDiseases,
		},
		{
			"CreateRegion",
			http.MethodPost,
			"/api/region",
			handleFunctions.RegionsAPI.CreateRegion,
		},
		{
			"DeleteRegion",
			http.MethodDelete,
			"/api/region/:regionId",
			handleFunctions.RegionsAPI.DeleteRegion,
		},
	}
}
